DBNAME = 'ControlGastos_PROD'
TRUSTED_CONNECTION = 'yes'
LOCAL = True

if LOCAL:
    SERVER = 'DESKTOP-0NB8DVB\SQLEXPRESS' #Server Seba 
STRING_CONNECTION = 'DRIVER={ODBC Driver 17 for SQL Server};SERVER='+SERVER+';DATABASE='+DBNAME+';Trusted_Connection='+TRUSTED_CONNECTION